### ISSUE TITLE
Attempt to better communicate the harrassment allegations

### ISSUE THREAD

**Issue by Songtech-0912** [Sneeds-Feed-and-Seed/sneedacity#120]
## Issue report

**Note: this is not a true bug report, the reasons why are mentioned explicitly below.**

I'm amazed that no contributors have mentioned the connection between this repo and <https://github.com/tenacityteam/tenacity/issues/99>. The rest of this issue will focus on discussing this issue.

With all due respect for the contributors and understanding of the slightly trollish motivations of this fork, I must mention that I have doubts as to whether this fork was made out of good faith. Below are some issues that deserve mention:

* The accusations of harrassment at [issue #99](https://github.com/tenacityteam/tenacity/issues/99) have not been mentioned - to me this is unprofessional given that there is a clear connection between the two repositories, with evidence of at least [one contributor](https://github.com/tenacityteam/tenacity/issues/99#issuecomment-875149313) and likely multiple contributors of sneedacity making targetted attempts attacking tenacity's (former) maintainer
* There is a clear link between sneedacity and the [4chan thread where tenacity's maintainer was attacked](https://boards.4channel.org/g/thread/82413768) quite viscerally and visibly, considering that many issues and even some of the wording in several files contain mentions to 4chan which suggest similar (if not the same) developers on both
* Without trying to go with an *ad hominem* attack here, I must point out that the author of the repo is very much beyond a doubt one of the original harrassers on 4chan given that many of the author's repos were mentioned by name on the same 4chan thread

In the interest of good faith, I would like to request fair, honest answers for all of the above points.

**Comment by thechron1c** [comment]
There have been enough archive snapshots and other things posted on other websites, the 4chan threads are archived and have been checked by many other people, stop harassing the good farmers of this repo and sneed someplace else.

**Comment by Kuprium** [comment]
https://desuarchive.org/g/thread/82436841/#q82436879

**Comment by ryusuke-okuno** [comment]
The "harrassement" you're talking about has no real evidence behind it other than the baseless claims of a mentally unstable person

**Comment by meguminloli** [comment]
> The accusations of harrassment at issue #99 have not been mentioned - to me this is unprofessional given that there is a clear connection between the two repositories, with evidence of at least one contributor and likely multiple contributors of sneedacity making targetted attempts attacking tenacity's (former) maintainer.

Why would we mention that? How are the accusations even related to this project? Why do you think that any of the members of this project tried to kill Cookie with a `butterfly knife`? Do you have any evidence that backs up your accusations?

> There is a clear link between sneedacity and the 4chan thread where tenacity's maintainer was attacked quite viscerally and visibly, considering that many issues and even some of the wording in several files contain mentions to 4chan which suggest similar (if not the same) developers on both

We suggest that this fork was brought by 4chan anons. Check the README.md . Anyway, a lot of people that have nothing to do with `4chan` are involved in this project. I was impressed to see that.

> Without trying to go with an ad hominem attack here, I must point out that the author of the repo is very much beyond a doubt one of the original harrassers on 4chan given that many of the author's repos were mentioned by name on the same 4chan thread

The owner of this project has nothing to do with all that situation. None of the owners of this organizations are involved in this. If you are gonna point out that I talked in HN, go ahead, but explain to me how asking for proof is trolling. 

Cookie started to harass us by telling people to report this repository without any real reason.

To everyone reading this, please stop trying to create a flame war here because we, the maintainers won't let you do that.

**Comment by atek64** [comment]
you have no evidence of any sort to be making any such accusations, especially when such accusations come directly from a compulsive liar. it's far from good faith when you come here to try and spread fud about a project, in an attempt to try and discredit it or destroy it, all due to personal agendas based on lies.

**Comment by NO-ob** [comment]
sneed

**Comment by nek0bit** [comment]
Feed

**Comment by weevilgit** [comment]
Man, 4chan is some kind of modern day Church of Satan. Ironic, tongue-in-cheek mean, and very tacky and lame if looked objectively--and consciously so, since being an internet cool/bad guy is seen as cringy to us (even saying we are a modern day c.o.s. is probably cringy enough.) But nonetheless taken completely serious by hysterical people like yourself, who honestly think there are evil nazis stabbing people for not naming their projects with Simpsons references.

Just as in the 90's some people wouldn't accept that Marilyn Manson, a nerdy kid dressing weird, wasn't actively trying to sacrifice babies and be possessed by satan, you guys won't accept that we aren't out here actually raping "trans folx of color" with over 9000 cis het nazi penises. Hell, you guys won't even accept the fact that "Sneed" is meaningless, and isn't a coded dog whistle slur to "special needs."

We are out here posting cartoon frogs and the dark night references, and you are losing your mind trying to figure out what coded cherokee we are spouting. That's really really funny.

![get a load](https://user-images.githubusercontent.com/69782583/124952939-0c346100-dfeb-11eb-8fbe-5f6cbd2e2a96.png)
