### ISSUE TITLE
XMPP server for sneedacity.

### ISSUE THREAD

**Issue by TheDuckWithAMonocle** [Sneeds-Feed-and-Seed/sneedacity#161]
Matrix is a honeypot. IRC is not secure. 
XMPP is much better. Would be perfect if we got a XMPP chatroom for resolving issues and whatnot. 
Goodday, and long live sneed.

**Comment by jobbautista9** [comment]
> Matrix is a honeypot. IRC is not secure.

[citation needed]

**Comment by eylles** [comment]
A room or an account on the matrix.org server is honeypot, using other homeserver or selfhosting is no prob.

**Comment by Ckath** [comment]
feel free to make an xmpp and pr it into readme, if its as peaceful as the irc maybe those could be bridged

**Comment by binex-dsk** [comment]
> > Matrix is a honeypot. IRC is not secure.
> 
> [citation needed]

https://lukesmith.xyz/articles/matrix-vs-xmpp

linked to israeli intelligence lol



> feel free to make an xmpp and pr it into readme, if its as peaceful as the irc maybe those could be bridged

i already made one, `sneedacity@rooms.swurl.xyz`

**Comment by jobbautista9** [comment]
> https://lukesmith.xyz/articles/matrix-vs-xmpp
> 
> linked to israeli intelligence lol
Good read, and I didn't know about Matrix's connection to Israeli intelligence, thanks. I already think that Matrix is bad, but I didn't think it can go any worse...

IRC is still hands-off the best in terms of simplicity. It doesn't support E2E, yes, and that's by design. Though you can try sending GPG-encrypted messages over IRC, that's possible. :P

**Comment by eylles** [comment]
@jobbautista9 if you use an intel cpu matrix having links to mossad is the least of your problems kek

**Comment by formerlychuck** [comment]
I'm not sure how Matrix is a honeypot when both the client and server code is FOSS and you can host your own instance, even if it was developed by le juice. Of course right now we're using the default instance instead of a self hosted one so that is an issue, but it's a public chatroom for anyone to join which makes any privacy concerns kind of pointless, unless you don't want your IP exposed to matrix.org

**Comment by binex-dsk** [comment]
> IRC is still hands-off the best in terms of simplicity. It doesn't support E2E, yes, and that's by design. Though you can try sending GPG-encrypted messages over IRC, that's possible. :P

i do agree, for people that don't really care about encryption and just want something that's easy to use, IRC is the way to go, and XMPP for people who want encryption and want to put in the time to use it.

and @Ckath i would PR the room into README but I don't really know where to put it. Would probably have to be put in a section with all the chatrooms already there
