### ISSUE TITLE
get rid of conan and get wxWidgets back to upstream or a new fork

### ISSUE THREAD

**Issue by Ckath** [Sneeds-Feed-and-Seed/sneedacity#47]
the current situation as I can tell from comments and the old issue at audacity(dont want to ping it) seem to agree on wxWidgets needing to come back to untouched upstream, or at least not the muse fork.

**Comment by meguminloli** [comment]
First of all, we would need to remove conan, because it makes the compilation a horrible job. 
Desu, if we remove conan, every single distro will adopt sneedacity.

**Comment by Ckath** [comment]
probably a better way to go about it, also hate the conan thing

**Comment by Furitenman** [comment]
Found the commit where they add this conan shit: https://github.com/audacity/audacity/commit/8aca9d02de3c69f718dd12822edb5393c58d29bf
I'll see if I can try and get rid of that shit and put the missing libraries on a PR.

**Comment by meguminloli** [comment]
Removing Conan isn't the easiest process. Beside this commit, they added 3 more dependencies. The latest legit commit of audacity is https://github.com/audacity/audacity/commit/90903d237ac8e07ef02a0fa73e4c1e4b516eb5a3 . The upcoming are adding conan, network-manager and other botnet/hard dependency.

**Comment by Furitenman** [comment]
Good catch, I'll see if I can remove conan, build and get the programme running. If there's errors I'll dig deeper into it.

**Comment by ChucksConsulting** [comment]
Isn't a bit premature to try to migrate to another version of wxWidgets when we can't even get the effects and generate menus working?

**Comment by meguminloli** [comment]
> Isn't a bit premature to try to migrate to another version of wxWidgets when we can't even get the effects and generate menus working?

Probably. Migrating to another version of wxWidgets shouldn't be a hard process if they didn't change the API. We should look into what changed from when Muse forked wxWidgets into upstream.

**Comment by Furitenman** [comment]
Update: We need to reintegrate zlib, libid3tag, libmp3lame, libmad and expat to the repo and cmake building to get rid of conan.

**Comment by formerlychuck** [comment]
I created a branch `wxwidgets` to explore migrating

**Comment by budRich** [comment]
I actually looked in to this some time ago, when it was first announced that telemetry would get add to audacity. My plan was to make a AUR package that would never update past the problematic version. Since Arch linux "always" provide the latest versions of stuff, i thought. 

But because of this insane wxwidget fork, which if i remember correctly, is in conflict with the regular wxwdigets library. Meaning that it is almost not possible to have them both installed at the same time.
The Arch package maintainers decided to not update audacity after that release (2.4.1). And therefor (and because i am lazy) i decided that i didn't have to worry about it myself either.

I just wanted to clarify for people stumbling in to this thread, that this is issue is **important**, and not having this dependency is: a win as big as getting rid of telemetry. I don't know for sure, but if Arch doesn't include later versions in their package repositories, I guess other distributions do that as well (debian).

With that said, maybe a future goal could be to move away from wxwidgets completely in favor of **sneedTK+2** .

btw I use Arch  
Have a nice day!

**Comment by Ckath** [comment]
my (futile) efforts of getting rid of conan, which are currently stuck on the whole ordeal with errors on MemoryX.h, are in the `conan_removal` branch for anyone who has the motivation

**Comment by binex-dsk** [comment]
"futile"

**Comment by mariaWitch** [comment]
Conan has been removed. The next step should be to look at upstreaming wxWidgets.

We should consider closing this issue and replacing it with a dedicated one for wxWidget.

**Comment by Ckath** [comment]
as conan is just sitting for some stability tests until merged I'm closing this in favor of a dedicated wxwidget issue
