### ISSUE TITLE
Disgusting

### ISSUE THREAD

**Issue by evokelektrique** [Sneeds-Feed-and-Seed/sneedacity#83]
https://github.com/tenacityteam/tenacity/issues/99

**Comment by jobbautista9** [comment]
...so your point being is?

**Comment by meguminloli** [comment]
> [tenacityteam/tenacity#99](https://github.com/tenacityteam/tenacity/issues/99)

How is this issue related to this repository?

**Comment by Ckath** [comment]
I'd urge to kindly stop derailing an honest audacity fork's issue page

**Comment by evokelektrique** [comment]
> > [tenacityteam/tenacity#99](https://github.com/tenacityteam/tenacity/issues/99)
> 
> How is this issue related to this repository?

Are you delusional or what?

**Comment by mariaWitch** [comment]
Again. How is that connected to this repository? We are further along in development than either Audacium or Tenacity.

**Comment by meguminloli** [comment]
> Are you delusional or what?
Come with proof that people involved in this project trolled Cookie.

**Comment by mckaygerhard** [comment]
the problem with open source fanatics are that does not understand the meaning of "team work", this project must almost try to collaborate with others event just "oh looks it's not our problem.. ja ja ja"

> Come with proof that people involved in this project trolled Cookie.

this is not the most polite way to said "hey we are nice and polite.. there's noone involving in that problem"

basically same shit happened with minetest.. developers improved the v5 and made a good work around API and so deep too much technicall things.. but players (in case of this issue is users) dont care about that "sh*t" cos those people have real life and not only like to be so tech-geek
